modules:
  TIME:
    enabled: true
  PTV:
    enabled: true
    routeName: 'Lillydale'
    stopName: 'Southern Cross'
    directionName: 'Lillydale'
    ptv_devid: NOT PROVIDED
    ptv_key: NOT PROVIDED
  WIFI:
    enabled: true
  BATTERY:
    enabled: true
